Document: hyperscan
Title: Debian hyperscan Manual
Author: <insert document author here>
Abstract: This manual describes what hyperscan is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hyperscan/hyperscan.sgml.gz

Format: postscript
Files: /usr/share/doc/hyperscan/hyperscan.ps.gz

Format: text
Files: /usr/share/doc/hyperscan/hyperscan.text.gz

Format: HTML
Index: /usr/share/doc/hyperscan/html/index.html
Files: /usr/share/doc/hyperscan/html/*.html
